server:
  port: 8889

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:8888
  cloud:
    gateway:
      routes:
        - id : CARGO-SERVICE
          uri: lb://CARGO-SERVICE
          predicates:
            - Path=/cargo/**
          filters:
            - name: CircuitBreaker
              args:
                name: CARGO-SERVICE
                fallbackuri: forward:/cargoServiceFallBack
        - id: TRANSACTION-SERVICE
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transaction/**
          filters:
            - name: CircuitBreaker
              args:
                name: TRANSACTION-SERVICE
                fallbackuri: forward:/transactionServiceFallBack
        - id: SHIPMENT-SERVICE
          uri: lb://SHIPMENT-SERVICE
          predicates:
            - Path=/shipment/**
          filters:
            - name: CircuitBreaker
              args:
                name: SHIPMENT-SERVICE
                fallbackuri: forward:/shipmentServiceFallBack

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}