server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shipmentDB
    username: postgres
    password: nadja
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: SHIPMENT-SERVICE




