server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cargoDB
    username: postgres
    password: nadja
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: CARGO-SERVICE




